---
- name: Pull docker image from dockerHub
  hosts: ubuntu18
  remote_user : kousthubh
  tasks:
    - name: Pull calculator image
      docker_image:
        name: kousthubh/spemini
        source: pull